### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2625]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
2 Errors

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
1. Reload game.
2. Buy weapon with command

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
1. 
[ERROR] gamemodes/darkrp/gamemode/modules/tipjar/cl_model.lua:123: attempt to compare nil with number
  1. func - gamemodes/darkrp/gamemode/modules/tipjar/cl_model.lua:123
   2. onModelUpdate - gamemodes/darkrp/gamemode/modules/tipjar/cl_model.lua:105
    3. unknown - gamemodes/darkrp/gamemode/modules/tipjar/cl_model.lua:117
     4. include - [C]:-1
      5. LoadModules - gamemodes/darkrp/gamemode/cl_init.lua:26
       6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:43

2.

[ERROR] gamemodes/darkrp/gamemode/modules/language/sh_language.lua:24: bad argument #2 to 'format' (no value)
  1. format - [C]:-1
   2. getPhrase - gamemodes/darkrp/gamemode/modules/language/sh_language.lua:24
    3. callback - gamemodes/darkrp/gamemode/modules/base/sv_purchasing.lua:49
     4. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
      5. RP_PlayerChat - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:78
       6. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:142

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
his addons :L

**Comment by Bo98** [comment]
Are you running the latest version? The first error should be fixed already. Second one shouldn't even happen unless I missed something.

**Comment by mcNuggets1** [comment]
Does still happen, when reloading DarkRP in local game.

Second Error is not reproduceable anymore for some reason.

**Comment by mcNuggets1** [comment]
Ok second Error is happening again, when trying to buy weapons as cook
using /buy 1.

**Comment by Bo98** [comment]
Did you have a translated language file? If so, could you show us what `weapon_` is set to?

**Comment by mcNuggets1** [comment]
Yeah, I see the mistake.
Well, thanks :D
