### ISSUE TITLE
DarkRP won't initialize

### ISSUE THREAD

**Issue by chadlrnsn** [FPtje/DarkRP#3269]
### Problem

This bug appears then you reconnecting after lua refreshing.

### Reproduction

1. Be on the server as player with admin rights and job with not index 1 or citizen
2. Go to your gamemode and resave `init.lua` and then resave `cl_init.lua` after it
3. You already will saw that your money and job disappeared
4. Reconnect to server  ( `retry` ) and.... you get it!

### Errors

no any errors 

### Additional Info

I assume this is due to initialization mis-synchronization.

**Comment by FPtje** [comment]
I think this has to do with a tradeoff with the simplerr module. That module wraps the loading of DarkRP's files in error handlers, so it can catch any errors, reword them, and give them back with extra explanations and tips.

The Lua refresh system is very hard to reason about. It's not entirely clear what it does and when, and how certain bugs with it manifest. There's also little control over what it does.

Are there specific errors that start appearing?

**Comment by chadlrnsn** [comment]
No, I don't have any errors. Wait a couple minutes, I'll upload the video.

**Comment by chadlrnsn** [comment]
https://youtu.be/O3pxb12IWP4

**Comment by FPtje** [comment]
Thanks to the help of @brandonsturgeon identifying the issue, I pushed a fix at e789a4fdc1ec5cdc2fcd1655b9e1270a28fe195a. Please try it out and see what happens.

I do hope that no addon used the debug functions to get those local variables in the script. 
Could you try out the latest Git version of DarkRP and see if that works better? Thanks!

**Comment by FPtje** [comment]
Closing for now assuming it is fixed.

**Comment by chadlrnsn** [comment]
Sorry for the long response. The bug still exists. I tried the latest commits 883a6a4602ef39c62b0bd1d435a1c4127581d932 and e789a4fdc1ec5cdc2fcd1655b9e1270a28fe195a, but game mode still stops working when updating `cl_init.lua` and `sv_init.lua` . 
I share [video](https://streamable.com/sphb8g) with you

**Comment by FPtje** [comment]
I see a message from EPOE saying "No access to server", but EPOE is not a DarkRP thing. That is its own thing.

By the way, the message about not having mounted CSS should also not be ignored. That will break things on its own.

**Comment by chadlrnsn** [comment]
> I see a message from EPOE saying "No access to server", but EPOE is not a DarkRP thing. That is its own thing.
> 
> By the way, the message about not having mounted CSS should also not be ignored. That will break things on its own.

Yes, I agree, issue "[DarkRP won't initialize](https://github.com/FPtje/DarkRP/issues/3269#top)" closed as resolved.
EPOE saying "No access to server" meaning that you dont have any rights as admin and that pointing us on thing that gamemode wont initialize some part of database or something like that, maybe it has something to do with initializing player rights. 

In general gamemode works good, thank you for fix!

**Comment by FPtje** [comment]
But the player rights are stored and then set by the admin mod. If you're using FAdmin to manage user rights, then that would be a bug for FAdmin. What admin mod are you using?

**Comment by chadlrnsn** [comment]
SAM. Is it bug of SAM?

**Comment by FPtje** [comment]
Possibly, you have to specifically have Lua refreshes in mind for things to work properly

**Comment by Srlion** [comment]
> SAM. Is it bug of SAM?

I think what you have right now happening is actually a really annoying thing to deal with, darkrp's fpp overrides `ply:SetUserGroup()` (It should probably not user ranks but rather permissions?) and sam does the same thing in `lua/sam/player/sh_player.lua`, so you need to figure out a way lol

Reloading a gamemode like darkrp doesn't seem a very nice thing to deal with

**Comment by FPtje** [comment]
Those overrides are a trigger for FPP to recalculate who can touch what. After all, if someone becomes admin, then they can suddenly do way more. It's an override because there is no real "user access changed" hook. 

It could be that reloading the gamemode causes the SAM override to be undone. I'm not sure what the exact consequences of that would be. Setting a user group should still be possible, even with that override.

I could change that code to only override the first time, but I think always running an old version of that function would cause bugs in FPP reloading 🤔

**Comment by Srlion** [comment]
Yeah, I also remember pulling my hair out because someone came to me with an issue with ranks not working correctly, just to find that if you have FPP from darkrp and FPP from workshop, they both would override SetUserGroup too lol.

FPP kinda looks spaghetti, so I assumed that it uses ranks for it :s

**Comment by FPtje** [comment]
Yeah overriding functions to use them as hooks has its downsides. There is quite some administrative effort to deal with e.g. the case where two instances of the same software are installed at once.

I suppose it's a fun challenge to figure out how to do function overrides in the presence of Lua reloading, multiple versions of the same addon being installed and other addons also overriding functions.

Ideally you'd be able to inspect the stack of function overrides and swap things out in those fun cases.
